# Generated by Django 5.2 on 2025-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
