# Generated by Django 5.1.8 on 2025-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_tg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tg_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
