# Generated by Django 5.2 on 2025-04-11 20:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habits",
            name="sign_pleasant_habit",
        ),
        migrations.AddField(
            model_name="habits",
            name="is_pleasant_habit",
            field=models.BooleanField(
                default=False, verbose_name="признак приятной привычки"
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.habits",
                verbose_name="связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="time_to_complete",
            field=models.TimeField(
                validators=[
                    django.core.validators.MaxValueValidator(datetime.time(0, 2))
                ],
                verbose_name="время для выполнения привычки",
            ),
        ),
    ]
