# Generated by Django 5.2 on 2025-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habits_sign_pleasant_habit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="last_performed_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
