# Generated by Django 5.2 on 2025-04-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habits_last_performed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1, null=True, verbose_name="периодичность"
            ),
        ),
    ]
