# Generated by Django 5.2 on 2025-04-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habits_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="is_pleasant_habit",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="признак приятной привычки",
            ),
        ),
    ]
