# Generated by Django 5.2 on 2025-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habits_is_pleasant_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="reward",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="вознаграждение"
            ),
        ),
    ]
