# Generated by Django 5.2 on 2025-04-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0008_habits_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habits",
            name="user",
        ),
    ]
