# Generated by Django 5.2 on 2025-04-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0009_remove_habits_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habits",
            name="last_performed_at",
        ),
    ]
